### PR TITLE
Revamped the site

### PR DESCRIPTION
**Pull request by PolarizedIons**
I redid the site styling, added skin-server status and some misc changes

### CODE REVIEW

**Comment by blha303** [comment]
Hey, I've had a lot on my plate in the last few days, I'll look at this and probably merge it when i get time :)

**Comment by blha303** [comment]
I've had the email for this in my inbox since december, I swear I'll get around to looking at it and pulling at at some point :P Hopefully by next december.

**Comment by blha303** [comment]
Sorry, this code base was always a huge mess. Thanks for writing this five years ago and sorry I never got back to it.

**Comment by PolarizedIons** [comment]
Haha, no worries :)

**Pull request closed without merging**
